export class EventManager {
    static init(): void;
    static queue: {};
    static zoom_changed_evt: string;
    static store_clickd_evt: string;
    static point_selected_evt: string;
    static config_changed: string;
    static path_substep_completed: string;
    static path_completed: string;
    static go_to_store_requested_evt: string;
    static resource_loaded_evt: string;
    static service_clicked_evt: string;
    static unit_pos_updated_evt: string;
    static floor_changed_evt: string;
    static on_enter_floor_navigation: string;
    static on_exit_floor_navigation: string;
    static on_enter_floor_selection: string;
    static on_exit_floor_selection: string;
    static on_enter_outside_navigation: string;
    static on_exit_outside_navigation: string;
    static step_selected_evt: string;
    static fire(event: any, payload: any): void;
    static on(event: any, callback: any): void;
    static fire_zoom_changed(zoom: any): void;
    static fire_store_selected(store_id: any): void;
    static fire_point_selected(hit_data: any): void;
    static fire_config_changed(): void;
    static fire_path_substep_completed(step_number: any): void;
    static fire_path_completed(): void;
    static fire_step_selected(step_index: any): void;
    static fire_go_to_store_requested(store_id: any): void;
    static fire_resource_loaded(resource: any): void;
    static fire_service_clicked(service: any): void;
    static fire_unit_position_updated(unit_data: any): void;
    static fire_floor_switched(floor_id: any): void;
    static fire_on_enter_floor_navigation(state: any): void;
    static fire_on_exit_floor_navigation(state: any): void;
    static fire_on_enter_floor_selection(state: any): void;
    static fire_on_exit_floor_selection(state: any): void;
    static fire_on_enter_outside_navigation(state: any): void;
    static fire_on_exit_outside_navigation(state: any): void;
}
