export { event_manager as EventManager };
declare const event_manager: EventManager;
declare class EventManager {
    init(): void;
    queue: {};
    zoom_changed_evt: string;
    store_clickd_evt: string;
    point_selected_evt: string;
    config_changed: string;
    path_substep_completed: string;
    path_completed: string;
    go_to_store_requested_evt: string;
    resource_loaded_evt: string;
    service_clicked_evt: string;
    unit_pos_updated_evt: string;
    floor_changed_evt: string;
    on_enter_floor_navigation: string;
    on_exit_floor_navigation: string;
    on_enter_floor_selection: string;
    on_exit_floor_selection: string;
    on_enter_outside_navigation: string;
    on_exit_outside_navigation: string;
    step_selected_evt: string;
    fire(event: any, payload: any): void;
    on(event: any, callback: any): void;
    fire_zoom_changed(zoom: any): void;
    fire_store_selected(store_id: any): void;
    fire_point_selected(hit_data: any): void;
    fire_config_changed(): void;
    fire_path_substep_completed(step_number: any): void;
    fire_path_completed(): void;
    fire_step_selected(step_index: any): void;
    fire_go_to_store_requested(store_id: any): void;
    fire_resource_loaded(resource: any): void;
    fire_service_clicked(service: any): void;
    fire_unit_position_updated(unit_data: any): void;
    fire_floor_switched(floor_id: any): void;
    fire_on_enter_floor_navigation(state: any): void;
    fire_on_exit_floor_navigation(state: any): void;
    fire_on_enter_floor_selection(state: any): void;
    fire_on_exit_floor_selection(state: any): void;
    fire_on_enter_outside_navigation(state: any): void;
    fire_on_exit_outside_navigation(state: any): void;
}
