import type { Vector2 } from "three";
export interface Input {
    active_input_module: any;
    dom_element: any;
    mouse_input_module: any;
    region: any;
    sub_region_element: any;
    touch_cooldown: any;
    touch_input_module: any;
    init(dom_element: any, sub_region_element: any): void;
    bind_events(): void;
    unbind_events(): void;
    on_wheel(event: any): void;
    on_touchstart(event: any): void;
    on_touchmove(event: any): void;
    on_touchcancel(event: any): void;
    on_touchend(event: any): void;
    on_mousedown(event: any): void;
    on_mousemove(event: any): void;
    on_mouseup(event: any): void;
    on_mouseleave(event: any): void;
    clear(): void;
    mouse_input_allowed(): boolean;
    set_mouse_input_active(): void;
    set_touch_input_active(): void;
    get left_mouse_button_pressed(): boolean;
    get left_mouse_button_down(): boolean;
    get left_mouse_button_released(): boolean;
    get right_mouse_button_pressed(): boolean;
    get right_mouse_button_down(): boolean;
    get right_mouse_button_released(): boolean;
    get middle_mouse_button_pressed(): boolean;
    get middle_mouse_button_down(): boolean;
    get middle_mouse_button_released(): boolean;
    get is_touchscreen(): boolean;
    get scroll_delta(): number;
    get zoom_delta(): number;
    get pointer_count(): number;
    get pointer_is_within_bounds(): boolean;
    pointer_is_over_element(elem: any): boolean;
    get pointers(): any;
    get pointer_pos(): any;
    get pointer_pos_delta(): any;
    get NDC(): Vector2;
    get NDC_delta(): Vector2;
    get pointer_center(): any;
    get pointer_center_delta(): any;
    get pointer_center_NDC(): any;
    get pointer_center_NDC_delta(): any;
    get_pointer_pos(index?: number): any;
    get_pointer_pos_delta(index?: number): any;
    get_pointer_NDC(index?: number): any;
    get_pointer_NDC_delta(index?: number): any;
    dispose(): void;
}
